Repository baniCsStudy/csStudy, pull requests merged in 2024-07, with the labels that each got.

#20 Feat: team1 os & computer 정리
  3. OS/3.1. OS & Computer/os&computer_team1.md
Labels: documentation, OS

#21 Feat: team1 os & computer url 연결
  README.md
Labels: documentation, OS

#22 Feat: memory_team1
  3. OS/3.2. Memory/memory_team1.md
  README.md
Labels: documentation, OS

#24 Feat: Process&Thread&Scheduling
  3. OS/3.3 Process & Thread/process&thread_team2.md
  3. OS/3.4 CPU scheduling algorithm/CPU scheduling algorithm_team2.md
  README.md
Labels: documentation, OS

#39 Feat: join
  4. DB/.gitkeep
  4. DB/4.6 Join/Join_team1.md
Labels: documentation, DB

#40 Feat: join
  README.md
Labels: documentation, DB

#41 Feat: complexity-team1
  5. Data Structure/.gitkeep
  5. Data Structure/5.1 Complexity/Complexity_team1.md
  README.md
Labels: documentation, Data Structure
